### ISSUE TITLE
Unable to install docker-casbin-plugin

### ISSUE THREAD

**Issue by meruvavenkatesh** [casbin/docker-casbin-plugin#27]
Hi,

I'm trying to following the steps to install docker-casbin-plugin and not able move forward.
That too code updated 4 years back.

Whether this plugin is working?
I'm following the link - https://casdoor.org/docs/basic/try-with-docker to install, But no luck for me.
Guide me on the same.

**Comment by hsluoyz** [comment]
@meruvavenkatesh what error did you encounter? Docs is: https://github.com/casbin/docker-casbin-plugin

Casdoor (https://casdoor.org/docs/basic/try-with-docker) is another project, which has nothing to do with this repo
